
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

setup.kibana:
  host: "kibana:5601"
  protocol: "http"

setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]