metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true

setup.dashboards:
  enabled: true

setup.kibana:
  host: "kibana:5601"
  protocol: "http"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
logging.to_files: false

